#!/usr/bin/env python

def weekday(year, month, day):
    offset = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
    week = ['Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday']
    afterFeb = 1
    if month > 2: afterFeb = 0
    aux = year - 1700 - afterFeb
    dayOfWeek = 5
    dayOfWeek += (aux + afterFeb) * 365
    dayOfWeek += aux / 4 - aux / 100 + (aux + 100) / 400
    dayOfWeek += offset[month -1] + (day - 1)
    dayOfWeek %= 7
    return week[int(dayOfWeek)]


def main():
    year = input('Year: ')
    month = input('Month: ')
    day = input('Day: ')
    _day = weekday(int(year), int(month), int(day))
    print(f"{year}/{month}/{day} fell on a {_day}")


if __name__ == "__main__":
    main()
