#!/usr/bin/env python

import os
import sys
from random import choice
from subprocess import Popen, PIPE


class Wallpaper:
    def __init__(self):
        #self.userdir = os.path.expanduser('~')
        self.userdir = '/home/geertje'
        self.fehbg = os.path.join(self.userdir, '.fehbg')
        self.picdir = os.path.join(self.userdir, 'Pictures')
        self.walldir = os.path.join(self.picdir, 'walls')
        self.sddm = '/usr/share/sddm/themes/mywall/Backgrounds/mywall.png'

    def read_fehbg(self):
        with open(self.fehbg, 'r') as feh:
            data = feh.read().splitlines()
        f = data[1].split(" ")[-2].split("/")[-1]
        f = f.replace("\'", "")
        return f


    def check_file(self, filename):
        remove = ['README', 'th_', 'thumb_']
        for check in remove:
            if filename.startswith(check):
                return True
        return False


    def read_folder(self, folders):
        data = []
        for folder in folders:
            start_path = os.path.join(self.walldir, folder)
            for path, _, files in os.walk(start_path):
                for filename in files:
                    if not self.check_file(filename):
                        full = os.path.join(path, filename)
                        data.append(full)


        data.sort()
        return data


    def generate_wallpaperlist(self, walltype):
        if walltype.lower() == 'all':
            walls = self.read_folder(['sfw', 'nsfw'])
        else:
            walls = self.read_folder([walltype])
        return walls

    def read_password(self):
        pword_file = '.config/ranwall/pword.txt'
        path = os.path.join(self.userdir, pword_file)
        with open(path, 'r') as file:
            pword = file.read().splitlines()[0]
        return pword


    def change_sddm_background(self, wallpaper: str):
        pword = self.read_password()
        dst = self.sddm

        if '.png' in wallpaper:
            cmd = f"cp {wallpaper} {dst}".split()
        else:
            cmd = f"convert {wallpaper} {dst}".split()

        args = ['sudo', '-S']
        p = Popen(args + cmd, stdin=PIPE,
                stderr=PIPE, universal_newlines=True)
        _ = p.communicate(pword + '\n')[1]


    def set_wallpaper(self, walltype: str):
        wallpapers = self.generate_wallpaperlist(walltype)
        wallpaper = self.read_fehbg()
        # notify = "notify-send -u low 'wallpaper set to "


        while wallpaper == self.read_fehbg():
            wallpaper = choice(wallpapers)
            # notify += wallpaper.split('/')[-1] + "'"

        os.system(f"feh --bg-scale {wallpaper}")
        # os.system(notify)
        self.change_sddm_background(wallpaper)


def main(category: str):
    wallpaper = Wallpaper()
    wallpaper.set_wallpaper(category)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Oops... no category given!")
        print("Please specify either sfw, nsfw or all.")
        sys.exit(1)

    main(sys.argv[1])
