#!/usr/bin/env python

"""
Random wallpaper changer
"""
import os
import sys
from random import choice
from subprocess import Popen, PIPE
from dataclasses import dataclass

@dataclass
class Settings:
    userdir: str
    fehbf: str
    picdir: str
    walldir: str
    walltype: str
    sddm: str
    currentwall: str


def initialize(category):
    Settings.userdir = os.path.expanduser('~')
    Settings.fehbg = os.path.join(Settings.userdir, '.fehbg')
    Settings.picdir = os.path.join(Settings.userdir, 'Pictures')
    Settings.walldir = os.path.join(Settings.picdir, 'walls')
    Settings.sddm = '/usr/share/sddm/themes/mywall/Backgrounds/mywall.png'
    
    with open(Settings.fehbg, 'r') as feh:
        data = feh.read().splitlines()
    f = data[1].split(" ")[-2].split("/")[-1]
    Settings.currentwall = f.replace("\'", "")
    Settings.walltype = category


def check_file(filename):
    remove = ['README', 'th_', 'thumb_']
    for check in remove:
        if filename.startswith(check):
            return True
    return False


def read_folder(folders):
    data = []
    for folder in folders:
        start_path = os.path.join(Settings.walldir, folder)
        for path, _, files in os.walk(start_path):
            for filename in files:
                if not check_file(filename):
                    full = os.path.join(path, filename)
                    data.append(full)
    data.sort()
    return data


def generate_wallpaperlist():
    if Settings.walltype.lower() == 'all':
        walls = read_folder(['sfw', 'nsfw', 'xmas'])
    else:
        walls = read_folder([Settings.walltype])
    return walls


def change_sddm_background(wallpaper):
    pword = ""
    pword_file = '.config/ranwall/pword.txt'
    path = os.path.join(Settings.userdir, pword_file)
    with open(path, 'r') as file:
        pword = file.read().splitlines()[0]

    if pword:
        dst = Settings.sddm
        if '.png' in wallpaper:
            cmd = f"cp {wallpaper} {dst}".split()
        else:
            cmd = f"convert {wallpaper} {dst}".split()
        args = ['sudo', '-S']
        p = Popen(args + cmd, stdin=PIPE,
            stderr=PIPE, universal_newlines=True)
        _ = p.communicate(pword + '\n')[1]
    else:
        print("ERROR: Could not read password file!")
        sys.exit(1)


def set_wallpaper():
    wallpapers = generate_wallpaperlist()
    wallpaper = Settings.currentwall
    while wallpaper == Settings.currentwall:
        wallpaper = choice(wallpapers)

    os.system(f"feh --bg-scale {wallpaper}")
    change_sddm_background(wallpaper)


def main(category):
    initialize(category)
    set_wallpaper()


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("ERROR:")
        print("  --> Please specify: all, xmas, sfw or nsfw")
        sys.exit(1)
    main(sys.argv[1])
