#!/usr/bin/env python

import os

def rename_files(files, prefix, startat):
    startat = int(startat)
    started = startat
    files.sort()
    for file in files:
        _, extension = os.path.splitext(file)
        new_name = f"{prefix}-{startat:04d}{extension}"
        print(f"  ==> {file} -> {new_name}")
        os.system(f"mv '{file}' '{new_name}'")
        startat += 1

    total = startat - started
    print(f"Renamed {total} files.")


def getdirlist(folder):
    jpg = [f for f in os.listdir(folder) if f.endswith('.jpg')]
    jpeg = [f for f in os.listdir(folder) if f.endswith('.jpeg')]
    png = [f for f in os.listdir(folder) if f.endswith('.png')]
    data = []
    data.extend(jpg)
    data.extend(jpeg)
    data.extend(png)
    return data


def main():
    yel = "\033[33;1m"
    res = "\033[0m"
    print(f"{yel}-= Renamer =-{res}")
    cwd = os.getcwd()
    files = getdirlist(cwd)
    prefix = input("> Prefix: ")
    startat = input("> Start at: ")
    rename_files(files, prefix, startat)


if __name__ == "__main__":
    main()
