#!/usr/bin/env python

import os
import sys
from subprocess import Popen, PIPE
from dataclasses import dataclass


@dataclass
class Settings:
    homedir: str
    iamgedir: str
    walldir: str
    current: str
    categories: list
    walls: list


def set_sddm_background(wallpaper):
    pword = ""
    pword_file = '.config/ranwall/pword.txt'
    path = os.path.join(Settings.homedir, pword_file)
    with open(path, 'r') as file:
        pword = file.read().splitlines()[0]

    if pword:
        dst = Settings.sddm
        if '.png' in wallpaper:
            cmd = f"cp {wallpaper} {dst}".split()
        else:
            cmd = f"convert {wallpaper} {dst}".split()
        args = ['sudo', '-S']
        p = Popen(args + cmd, stdin=PIPE,
            stderr=PIPE, universal_newlines=True)
        _ = p.communicate(pword + '\n')[1]
    else:
        sys.exit(1)


def initialize():
    Settings.homedir = os.path.expanduser("~")
    Settings.imagedir = os.path.join(Settings.homedir, 'Pictures')
    Settings.walldir = os.path.join(Settings.imagedir, 'walls')
    Settings.categories = ['sfw', 'nsfw', 'xmas']
    Settings.sddm = '/usr/share/sddm/themes/mywall/Backgrounds/mywall.png'
    
    # --- Get current wallpaper from .fehbg
    fehbg = os.path.join(Settings.homedir, '.fehbg')
    with open(fehbg, 'r') as file:
        data = file.read().splitlines()
    current = data[-1].split(' ')[-2].split('/')[-1]
    current = current.replace("'", "")
    Settings.current = current


def determine_next():
    print(Settings.current)
    prefix = Settings.current.split('-')[0]
    number = Settings.current.split('-')[1].split('.')[0]
    ext = Settings.current.split('-')[1].split('.')[1]
    next = int(number) + 1
    new = f"{prefix}-{next:04d}.{ext}"
    
    print(new)



def main():
    initialize()
    determine_next()


if __name__ == "__main__":
    main()
