#!/usr/bin/env python
#
# A simple script to help me during writing my stupid
# stories.
#

import os
import random
from shutil import copy2
from colors import *

def clear():
    os.system('clear')


def set_wm_class(title):
  print(f'\x1b]0;{title}\x07')


def wait_for_enter():
    _ = input('Press [ENTER]...')


def show_title():
    yel = Colors.fgBrightYellow
    res = Colors.reset
    print(f"{yel}  -= WRTR =-{res}")
    print()


def readlist(filename: str) -> list:
    """Read contents of file and return it as a list."""
    home = os.path.expanduser('~')
    path = f"{home}/.local/share/wrtr/{filename}.lst"
    data = []
    with open(path, 'r') as file:
        data = file.read().splitlines()
    return data


def choose(what='f'):
    gre = Colors.fgBrightGreen
    res = Colors.reset

    chosen = ''
    if what == 'f':
        chosen = random.choice(readlist('girlnames'))
    elif what == 'm':
        chosen = random.choice(readlist('boynames'))
    elif what == 'h':
        chosen = random.choice(readlist('hotres'))
    elif what == 'b':
        chosen = random.choice(readlist('bnb'))
    elif what == 's':
        chosen = random.choice(readlist('streets'))
    elif what == 't':
        chosen = random.choice(readlist('towns'))

    print(f"What about {gre}{chosen}{res} ?")
    print()
    wait_for_enter()


def show_menu() -> str:
    """Generate menu and return user input as string."""
    yel = Colors.fgBrightYellow
    red = Colors.fgBrightRed
    res = Colors.reset

    options = [
            'girl name',
            'boy name',
            'hotel/resport name',
            'b&b name',
            'street name',
            'town name',
            ]
    allowed = []
    clear()
    show_title()

    for c, item in enumerate(options):
        print(f"{yel}{c + 1}{res}. {item}")
        allowed.append(str(c + 1))

    allowed.extend(['q', 't', 'c', 'k'])

    print()
    print(f'{yel}c{res}. convert C to F')
    print(f'{yel}k{res}. convert Km to M')
    print(f'{yel}t{res}. copy template')
    print(f'{red}q{res}. exit')
    print()

    answer = ''
    while answer not in allowed:
        answer = input("> ")

    return answer.lower()


def c_to_f():
    celsius = input('Celsius: ')
    fahrenheit = (int(celsius) * 9/5) + 32
    print(f">> {fahrenheit}")
    wait_for_enter()


def k_to_m():
    km = int(input('Km: '))
    conv_fac = 0.621371

    miles = round(km * conv_fac)

    print(f">> {miles}")
    wait_for_enter()


def copy_template():
    gre = Colors.fgBrightGreen
    res = Colors.reset

    home = os.path.expanduser('~')
    src = f"{home}/.local/share/wrtr/template.md"

    _name = input("New story name without .md : ")
    newname = _name + ".md"
    notes = _name + ".notes.toml"

    curpath = os.getcwd()
    dst = os.path.join(curpath, newname)
    nts = os.path.join(curpath, notes)

    copy2(src, dst)
    file = open(nts, "w+")
    file.write(f"# {newname} notes\r\n")
    file.write(f"\r\n")
    file.close()

    print(f"  {gre}Template copied to {newname}{res}")
    print(f"  {gre}Notes file created: {notes}{res}")
    print()
    wait_for_enter()


def main():
    """The main loop."""
    set_wm_class('wrtr')
    answer = show_menu()

    if answer == 'q':
        exit(0)
    elif answer == 't':
        copy_template()
    elif answer == 'c':
        c_to_f()
    elif answer == 'k':
        k_to_m()
    elif int(answer) == 1:
        choose('f')
    elif int(answer) == 2:
        choose('m')
    elif int(answer) == 3:
        choose('b')
    elif int(answer) == 4:
        choose('h')
    elif int(answer) == 5:
        choose('s')
    elif int(answer) == 6:
        choose('t')


if __name__ == '__main__':
    while True:
        main()
